set encoding=UTF-8

set shiftwidth=4
set tabstop=4
set expandtab
set autoindent

set smarttab

" Incremental search
set incsearch

" Line Numbering
set number
set relativenumber

" Make it obvious where 80 characters is
set textwidth=80

set colorcolumn=+1
set scrolloff=10

set clipboard^=unnamed,unnamedplus


syntax on
colorscheme monokai

" re-map the escape key for leaving insert mode
inoremap jk <ESC>
vnoremap jk <Esc>

" Ingore Ex mode
map Q <Nop>

" Stay in visual mode when indenting
vnoremap < <gv
vnoremap > >gv

nnoremap Y yg$

" move lines up and down. 
" In normal mode or in insert mode, press Alt-j to move the current line down, 
" or press Alt-k to move the current line up.
" After visually selecting a block of lines (for example, by pressing V then
" moving the cursor down), press Alt-j to move the whole block down, or press
" Alt-k to move the block up. from here, but this uses alt which somehow was not
" working. 
" https://vim.fandom.com/wiki/Moving_lines_up_or_down

nnoremap <C-j> :m+<CR>==
nnoremap <C-k> :m-2<CR>==
inoremap <C-j> <Esc>:m+<CR>==gi
inoremap <C-k> <Esc>:m-2<CR>==gi
vnoremap <C-j> :m'>+<CR>gv=gv
vnoremap <C-k> :m-2<CR>gv=gv

# select everything
nnoremap <C-a> ggVG


" For me, Vim stopped being able to copy to the * and + registers over SSH, 
" even though :echo has('clipboard') was 1, and other X programs still worked. 
" The solution for me was to add a mapping that yanks (via a register) to xclip:
" It's a hack, and there surely must be a better way.
" But in the end, who cares really?
vnoremap <silent><Leader>y +yy <Bar> :call system('xclip', @y)<CR>

" I want to keep clipboard when pasting 
xnoremap p P


call plug#begin()
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'


" Make sure you use single quotes
Plug 'michaeljsmith/vim-indent-object'
call plug#end()

