set encoding=UTF-8

set shiftwidth=4
set tabstop=4
set expandtab
set autoindent

set smarttab


" Line Numbering
set number
set relativenumber

" Make it obvious where 80 characters is
set textwidth=80

set colorcolumn=+1

syntax on
colorscheme monokai

" re-map the escape key for leaving insert mode
inoremap jk <ESC>

" Ingore Ex mode
map Q <Nop>

" Stay in visual mode when indenting
vnoremap < <gv
vnoremap > >gv

" insert (static) multi-line text, calls function, which prints out the file
nmap ^N :call Class()<CR>
function! Class()
    " ~/vim/cpp/rectangle.txt is the path to the template file
    r~/.vim/dir/rectangle.txt
endfunction



