# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
COMPLETION_WAITING_DOTS="false"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"


# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

VIM_MODE_VICMD_KEY='jk'


plugins=(git
	zsh-syntax-highlighting
	zsh-autosuggestions
	zsh-vim-mode
    zsh-autocomplete
    fzf
	)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"
#
ZSH_AUTOSUGGEST_STRATEGY=(history completion)



alias 'fresh'='cd ~/fresh-install'
alias 'black'='black --line-length=79 --skip-string-normalization'
alias fcf='test -d "$(fzf)" || : $_:h; cd -- $_'
alias fyf='vim $(fzf)'
alias fff='echo $(fzf) | xsel -b'
alias fof='xdg-open $(fzf)'

alias o='xdg-open'
alias fresh='cd ~/fresh-install && git pull'
alias yk='xsel -i -b'
alias upup='sudo apt-get update && sudo apt-get upgrade'
alias 'yk'='xsel -i -b'
alias 'fresh'='cd ~/fresh-install && git pull'

# cd "$(command)" to jump to result of original path of soft link Ω(Φ(X))
alias 'src'='cd "$(readlink -f `which ~/src` | head -n 1)"'
# Shows the current semester week (needs to be updated after each semester)
alias sw='echo $(($(date +%U)-7))'

alias vz='vim ~/.zshrc && source ~/.zshrc'
alias vv='vim ~/.vimrc'

# shortcut to the git alias
alias f='git f '

# use the fzf command to select a file or directory 
# and then change the current working directory to the selected path
alias fcf='test -d "$(fzf)" || : $_:h; cd -- $_'

# copy result of fzf to clipboard
alias fff='echo $(fzf) | xsel -b'

alias fof='xdg-open $(fzf)'

# show print statement in pytest (don't capture STOUT)
alias pytest='pytest -s'

# git aliases
alias 'git diff'='git diff --ignore=*.xml' # Almost never do I care for xml files



# adb: this is meant to be run on the device
# putting it here for reference
alias adb_set_proxy="adb shell settings put global http_proxy $(ip -o -4 addr show ens33 | awk '{print $4}' | sed 's/\/.*//g'):8080"

alias adb_unset_proxy="adb shell settings put global http_proxy  :0"
 
# git pull all directories depth 1
function pullall () {
/usr/bin/ls | xargs -P10 -I{} git -C {} pull
}


function gs() {
    local selected_branch=$(git branch | fzf)
    selected_branch="$(echo "$selected_branch" | xargs)" # handy way to remove whitespace

    git switch ${selected_branch}
    
     if [ $? -ne 0 ]; then
         if [ "$(git branch --show-current)" = "$selected_branch" ]; then
              echo "Already on branch $selected_branch !"
         fi
     fi
}



# Navigation
function .. () { cd .. }
function ... () { cd ../.. }
function .... () { cd ../../.. }
function ..... () { cd ../../../.. }


# grep *docx and *docm files
docxgrep() {
    if [[ -z $1 ]]; then
        echo "Usage: docxgrep <keyword>"
        return 1
    fi
    
    keyword="$1"
    
    /usr/bin/fdfind -t f -e docx -e docm . | while read -r arg; do
        if unzip -p "$arg" 2>/dev/null | rg -q  --ignore-case --fixed-strings "$keyword"; then
            echo "$arg"
        fi
    done
}





#### Block is responsible for activating ssh agent upon login
# We could solve this with systemd, but I prefer having all config and so on
# and so forth in one place, the zshrc.
SSH_ENV="$HOME/.ssh/agent-environment"
function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi
#####
#
#
HISTFILE=~/.zsh_history
HISTSIZE=999999999 # I don't think zsh has a setting that means “infinite”, but for all practical purpose, one billion is infinite.
SAVEHIST=$HISTSIZE

# Prevent vim freeze acccidentally
stty -ixon 

# Load environment variables
if [ -f ~/.bash_profile ]; then 
    . ~/.bash_profile;
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh



